version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements.txt

sphinx:
  builder: dirhtml
  fail_on_warning: true
  configuration: docs/conf.py
