# Open up a Team Meeting issue to prep for the meeting
name: Create an issue on push
on:
  schedule:
    # 25th day of the month, so we have a bit of lead time before the next meeting
    - cron: '0 0 25 * *'
  workflow_dispatch:
    
jobs:
  create-team-issue:
    runs-on: ubuntu-latest
    with:
      filename: .github/ISSUE_TEMPLATE/team-meeting.md
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
